package io.github.fletchmckee.liquid.samples.app.domain.entity

import kotlinx.datetime.Clock
import kotlinx.datetime.LocalDate
import kotlinx.datetime.LocalTime
import kotlinx.datetime.TimeZone
import kotlinx.datetime.todayIn

/**
 * Source of a meeting — distinguishes Klik backend meetings from locally imported Apple Calendar events.
 */
enum class MeetingSource {
    KLIK,
    APPLE_CALENDAR
}

/**
 * Domain entity representing a meeting.
 * This is the business/domain model used throughout the app.
 */
data class Meeting(
    val id: String,
    val title: String,
    val date: LocalDate,
    val time: String,
    val participants: List<Person>,
    val summary: String,
    val actionItems: List<TodoItem>,
    val minutes: List<MeetingMinute> = emptyList(),
    val transcript: String? = null,
    val isPinned: Boolean = false,
    val isArchived: Boolean = false,
    val pinnedAt: Long? = null,
    val dropboxUrl: String? = null,
    val source: MeetingSource = MeetingSource.KLIK,
    val sourceColor: Long? = null // ARGB color from Apple Calendar (null = use default)
) {
    /**
     * Parsed start time from the time string (format: "HH:mm" or "H:mm AM/PM")
     */
    val startTime: LocalTime
        get() {
            return try {
                // Handle formats like "9:00 AM", "10:30 AM", "2:00 PM"
                val cleanTime = time.uppercase().trim()
                val isPM = cleanTime.contains("PM")
                val timeOnly = cleanTime.replace("AM", "").replace("PM", "").trim()
                val parts = timeOnly.split(":")
                var hour = parts[0].toInt()
                val minute = if (parts.size > 1) parts[1].toInt() else 0

                if (isPM && hour != 12) hour += 12
                if (!isPM && hour == 12) hour = 0

                LocalTime(hour, minute)
            } catch (e: Exception) {
                LocalTime(9, 0) // Default to 9:00 AM if parsing fails
            }
        }

    /**
     * Whether this meeting is in the past
     */
    val isPast: Boolean
        get() {
            val today = Clock.System.todayIn(TimeZone.currentSystemDefault())
            return date < today
        }

    /**
     * Todos as list of strings (from action items) - used by CalendarScreen
     */
    val todos: List<String>
        get() = actionItems.map { it.text }

    /**
     * Transcript lines as pairs (speaker, text) - used by CalendarScreen
     * Handles formats:
     * - "Speaker Name: Message text"
     * - "[00:00 - 0:00:01] Speaker Name: Message text"
     */
    val transcriptLines: List<Pair<String, String>>
        get() = transcript?.split("\n")?.mapNotNull { line ->
            val trimmedLine = line.trim()
            if (trimmedLine.isEmpty()) return@mapNotNull null

            // Check if line starts with timestamp like [00:00 - 0:00:01]
            val timestampRegex = Regex("^\\[([^\\]]+)\\]\\s*")
            val matchResult = timestampRegex.find(trimmedLine)

            val (timestamp, restOfLine) = if (matchResult != null) {
                val ts = matchResult.groupValues[1]
                val rest = trimmedLine.substring(matchResult.range.last + 1).trim()
                ts to rest
            } else {
                null to trimmedLine
            }

            // Find the LAST colon that separates speaker from message
            // This handles speaker names that might contain timestamps
            val colonIndex = restOfLine.indexOf(": ")
            if (colonIndex > 0) {
                val speaker = restOfLine.substring(0, colonIndex).trim()
                val text = restOfLine.substring(colonIndex + 2).trim()
                // Include timestamp with speaker if present
                val speakerWithTime = if (timestamp != null) "[$timestamp] $speaker" else speaker
                speakerWithTime to text
            } else {
                // No colon found, treat whole line as text
                (timestamp ?: "") to restOfLine
            }
        } ?: emptyList()
}

data class MeetingMinute(
    val category: String,
    val items: List<String>
)

/**
 * Daily briefing generated by AI
 */
data class DailyBriefing(
    val summary: String,
    val meetingCount: Int,
    val focusAreas: List<String>,
    val topPriority: String?,
    val generatedAt: Long
) {
    /**
     * Alias for summary - used by CalendarScreen
     */
    val briefingText: String get() = summary
}

/**
 * Traced segment from backend APIs (insights, encourage, worklife)
 * Provides evidence for AI-generated content by linking back to source meeting segments
 */
data class TracedSegment(
    val sessionId: String,
    val segmentId: String,
    val text: String,
    val score: Float,
    val speakerName: String? = null,
    val meetingTitle: String? = null,
    val meetingTime: String? = null,
    val matchedKeywords: List<String> = emptyList()
)

/**
 * User-specific insights from KLIK Insights API
 */
data class Insights(
    val summary: String,
    val highlights: List<String> = emptyList(),
    val recommendations: List<String> = emptyList(),
    val tracedSegments: List<TracedSegment> = emptyList(),
    val generatedAt: Long = 0L
) {
    /**
     * Main insight text for display
     */
    val insightText: String get() = summary
}
